<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:cmn="http://kyc-payments.com/CommonTypes"
           targetNamespace="http://kyc-payments.com/CommonTypes"
           elementFormDefault="qualified">

    <xs:complexType name="PaymentData">
        <xs:sequence>
            <xs:element name="bill" type="xs:integer" />
            <xs:element name="channel" type="xs:integer" />
            <xs:element name="method" type="xs:integer" />
            <xs:element name="amount" type="xs:double" />
            <xs:element name="motive" type="xs:string" />
            <xs:element name="reference" type="xs:string" />
            <xs:element name="office" type="xs:integer" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ReceiptData">
        <xs:sequence>
            <xs:element name="folio" type="xs:integer"/>
            <xs:element name="amount" type="xs:double"/>
            <xs:element name="date" type="xs:dateTime"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="HistoricalPaymentCriteria">
        <xs:sequence>
            <xs:element name="customer" type="xs:long" minOccurs="0"/>
            <xs:element name="start" type="xs:date" />
            <xs:element name="finish" type="xs:date" />
            <xs:element name="limit" type="xs:integer"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="PaymentRecord">
        <xs:sequence>
            <xs:element name="bill" type="xs:long"/>
            <xs:element name="folio" type="xs:long"/>
            <xs:element name="channel" type="xs:string"/>
            <xs:element name="amount" type="xs:double"/>
            <xs:element name="method" type="xs:string" />
            <xs:element name="reference" type="xs:string"/>
            <xs:element name="status" type="cmn:StatusPaymentCategory"/>
            <xs:element name="date" type="xs:dateTime"/>
            <xs:element name="office" type="xs:string" />
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="StatusPaymentCategory">
        <xs:restriction base="xs:string">
            <xs:enumeration value="REJECTED" />
            <xs:enumeration value="PAID" />
            <xs:enumeration value="ONGOING" />
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="CustomerPaymentMethod">
        <xs:sequence>
            <xs:element name="method" type="xs:integer" />
            <xs:element name="account" type="xs:string"/>
            <xs:element name="directDebit" type="xs:boolean"/>
            <xs:element name="authorize" type="xs:boolean"/>
            <xs:element name="active" type="xs:boolean"/>
        </xs:sequence>
    </xs:complexType>

</xs:schema>