<?xml version="1.0" encoding="utf-8"?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  xmlns:pym="http://kyc-payments.com/PaymentTypes"
                  xmlns:tns="http://kyc-payments.com/PaymentTypes"
                  targetNamespace="http://kyc-payments.com/PaymentTypes">
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
            <xs:import namespace="http://kyc-payments.com/PaymentTypes" elementFormDefault="qualified" schemaLocation="PaymentTypes.xsd"/>
        </xs:schema>
    </wsdl:types>

    <wsdl:message name="MakePaymentRequest">
        <wsdl:part element="pym:MakePaymentRequest" name="MakePaymentRequest" />
    </wsdl:message>

    <wsdl:message name="MakePaymentResponse">
        <wsdl:part element="pym:MakePaymentResponse" name="MakePaymentResponse" />
    </wsdl:message>

    <wsdl:message name="GetHistoricalPaymentsRequest">
        <wsdl:part element="pym:GetHistoricalPaymentsRequest" name="GetHistoricalPaymentsRequest" />
    </wsdl:message>

    <wsdl:message name="GetHistoricalPaymentsResponse">
        <wsdl:part element="pym:GetHistoricalPaymentsResponse" name="GetHistoricalPaymentsResponse" />
    </wsdl:message>

    <wsdl:message name="GetPaymentRequest">
        <wsdl:part element="pym:GetPaymentRequest" name="GetPaymentRequest" />
    </wsdl:message>

    <wsdl:message name="GetPaymentResponse">
        <wsdl:part element="pym:GetPaymentResponse" name="GetPaymentResponse" />
    </wsdl:message>

    <wsdl:message name="UpdateCustomerPaymentMethodRequest">
        <wsdl:part element="pym:UpdateCustomerPaymentMethodRequest" name="UpdateCustomerPaymentMethodRequest" />
    </wsdl:message>

    <wsdl:message name="UpdateCustomerPaymentMethodResponse">
        <wsdl:part element="pym:UpdateCustomerPaymentMethodResponse" name="UpdateCustomerPaymentMethodResponse" />
    </wsdl:message>

    <wsdl:message name="GetCustomerPaymentMethodRequest">
        <wsdl:part element="pym:GetCustomerPaymentMethodRequest" name="GetCustomerPaymentMethodRequest" />
    </wsdl:message>

    <wsdl:message name="GetCustomerPaymentMethodResponse">
        <wsdl:part element="pym:GetCustomerPaymentMethodResponse" name="GetCustomerPaymentMethodResponse" />
    </wsdl:message>

    <wsdl:portType name="PaymentsPortType">

        <wsdl:operation name="MakePayment">
            <wsdl:input message="tns:MakePaymentRequest" name="MakePaymentRequest" />
            <wsdl:output message="tns:MakePaymentResponse" name="MakePaymentResponse" />
        </wsdl:operation>

        <wsdl:operation name="GetHistoricalPayments">
            <wsdl:input message="tns:GetHistoricalPaymentsRequest" name="GetHistoricalPaymentsRequest" />
            <wsdl:output message="tns:GetHistoricalPaymentsResponse" name="GetHistoricalPaymentsResponse" />
        </wsdl:operation>

        <wsdl:operation name="GetPayment">
            <wsdl:input message="tns:GetPaymentRequest" name="GetPaymentRequest" />
            <wsdl:output message="tns:GetPaymentResponse" name="GetPaymentResponse" />
        </wsdl:operation>

        <wsdl:operation name="UpdateCustomerPaymentMethod">
            <wsdl:input message="tns:UpdateCustomerPaymentMethodRequest" name="UpdateCustomerPaymentMethodRequest" />
            <wsdl:output message="tns:UpdateCustomerPaymentMethodResponse" name="UpdateCustomerPaymentMethodResponse" />
        </wsdl:operation>

        <wsdl:operation name="GetCustomerPaymentMethod">
            <wsdl:input message="tns:GetCustomerPaymentMethodRequest" name="GetCustomerPaymentMethodRequest" />
            <wsdl:output message="tns:GetCustomerPaymentMethodResponse" name="GetCustomerPaymentMethodResponse" />
        </wsdl:operation>

    </wsdl:portType>

    <wsdl:binding name="PaymentsPortTypeSoap11" type="tns:PaymentsPortType">

        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>

        <wsdl:operation name="MakePayment">
            <soap:operation soapAction=""/>
            <wsdl:input name="MakePaymentRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="MakePaymentResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="GetHistoricalPayments">
            <soap:operation soapAction=""/>
            <wsdl:input name="GetHistoricalPaymentsRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="GetHistoricalPaymentsResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="GetPayment">
            <soap:operation soapAction=""/>
            <wsdl:input name="GetPaymentRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="GetPaymentResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="UpdateCustomerPaymentMethod">
            <soap:operation soapAction=""/>
            <wsdl:input name="UpdateCustomerPaymentMethodRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="UpdateCustomerPaymentMethodResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>

        <wsdl:operation name="GetCustomerPaymentMethod">
            <soap:operation soapAction=""/>
            <wsdl:input name="GetCustomerPaymentMethodRequest">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="GetCustomerPaymentMethodResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>

    <wsdl:service name="KYCPayments">
        <wsdl:port binding="tns:PaymentsSoap11" name="PaymentsSoap11">
            <soap:address location=" http://localhost:9007/kyc/soap/KYCPayments/"/>
        </wsdl:port>
    </wsdl:service>

</wsdl:definitions>