spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kyc_database
    username: kyc_user
    password: kyc_pass
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 1
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

kyc-config:
  services:
    kyc-users: http://localhost:9004

service:
  url: http://localhost:9008/kyc/soap/KYCPayments

logging:
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    org.springframework.ws.server.MessageTracing.sent: TRACE
    org.springframework.ws.server.MessageTracing.received: TRACE