spring:
  application:
    name: kyc-payments
  profiles:
    active: dev
  webservices:
    path: /kyc
  jpa:
    open-in-view: false

server:
  port: 9008

management:
  endpoints:
    web:
      exposure:
        include: info,health
  endpoint:
    health:
      show-details: always
  health:
    diskspace:
      enabled: false

kyc-messages:
  catalog:
    messages:
      "001":
        code: KYC-PAYMENTS-001
        message: Unexpected Error
        type: ERROR
        hint: UNEXPECTED
      "002":
        code: KYC-PAYMENTS-002
        message: The operation is not allowed
        type: ERROR
        hint: AUTH
      "003":
        code: KYC-PAYMENTS-003
        message: The data are invalid
        type: ERROR
      "004":
        code: KYC-PAYMENTS-004
        message: The payment cannot be processed
        type: ERROR
      "005":
        code: KYC-PAYMENTS-005
        message: The operation could not be performed at this moment
        type: ERROR