spring:
  datasource:
    url: ${kyc.config.database.postgresql.url}
    username: ${kyc.config.database.postgresql.username}
    password: ${kyc.config.database.postgresql.secret}
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

logging:
  file:
    name: /opt/kyc/logs/${spring.application.name}.log
  logback:
    rollingpolicy:
      file-name-pattern: /opt/kyc/logs/${spring.application.name}/%d{yyyy-MM-dd}.%i.log.gz
      max-file-size: 50MB
      max-history: 30
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    org.springframework.ws.server.MessageTracing.sent: INFO
    org.springframework.ws.server.MessageTracing.received: INFO