
DROP TABLE IF EXISTS KYC_USER_LOGIN;
DROP TABLE IF EXISTS KYC_USER;
DROP TABLE IF EXISTS KYC_USER_TYPE;

CREATE TABLE KYC_USER(
    ID SERIAL,
    USERNAME VARCHAR(10) NOT NULL,
    SECRET VARCHAR(100) NOT NULL,
    ACTIVE BOOLEAN NOT NULL,
    LOCKED BOOLEAN NOT NULL,
    USER_TYPE INTEGER NOT NULL,
    DATE_CREATION DATE NOT NULL,
    DATE_UPDATED DATE,
    ID_PERSON INTEGER
);

CREATE TABLE KYC_USER_TYPE(
	ID SERIAL,
	DESCRIPTION VARCHAR(20)
);

CREATE TABLE KYC_USER_LOGIN(
	ID SERIAL,
	DATE_LOGIN DATE,
	SUCCESSFUL_LOGIN BOOLEAN,
	ATTEMPTS_LOGIN INTEGER,
	ID_USER INTEGER
);

ALTER TABLE KYC_USER ADD PRIMARY KEY(ID);
ALTER TABLE KYC_USER_TYPE ADD PRIMARY KEY(ID);
ALTER TABLE KYC_USER_LOGIN ADD PRIMARY KEY(ID);

ALTER TABLE KYC_USER ADD CONSTRAINT FK_KYC_USER_TYPE
FOREIGN KEY (USER_TYPE) REFERENCES KYC_USER_TYPE(ID) ON DELETE CASCADE;

ALTER TABLE KYC_USER ADD CONSTRAINT FK_KYC_ID_PERSON
FOREIGN KEY (ID_PERSON) REFERENCES CUSTOMER(ID) ON DELETE CASCADE;

ALTER TABLE KYC_USER_LOGIN ADD CONSTRAINT FK_ID_USER
FOREIGN KEY (ID_USER) REFERENCES KYC_USER(ID) ON DELETE CASCADE;

INSERT INTO KYC_USER_TYPE(DESCRIPTION) VALUES('CUSTOMER');
INSERT INTO KYC_USER_TYPE(DESCRIPTION) VALUES('EXECUTIVE');

INSERT INTO KYC_USER(USERNAME,SECRET,ACTIVE,LOCKED,USER_TYPE,DATE_CREATION)
VALUES('LHPH','$2a$10$TWnYBloz46640OYc58z3ReMaJEKy4ACT1U2fAi1FINWyGF6TTdVF6',TRUE,FALSE,1,NOW());